version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_DB=authz
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Ninjadev1$$
    ports:
      - "5432:5432"  
  web:
    build: .
    volumes:
      - .:/code
      - ${HOME}/.aws/credentials:/root/.aws/credentials:ro
    ports:
      - "5000:5000"
    env_file:
      - .env  
    depends_on:
      - db